### ISSUE TITLE
Spinning cursor on payment details page

### ISSUE THREAD

**Issue by natea** [django-oscar/django-oscar-stripe#3]
I've added the django-oscar-stripe plugin (tried the redpandalabs and labxio forks) to my django-oscar project, and when I get to the Enter Payment Details page, and click the "Pay with Card" button, the spinning cursor appears but it doesn't do anything. Looking at the web developer console, there is nothing appearing in the console. Here is a screenshot of the network activity:

![screenshot 2014-04-29 10 57 00](https://cloud.githubusercontent.com/assets/118984/2832966/d4e45e18-cfca-11e3-9c17-bdcf0460148f.png)

I've checked my Stripe API keys and they are correct, and I'm accessing it via shared SSL cert on Heroku (https). Any ideas why it's not working?

**Comment by maiksprenger** [comment]
Nate, I'm afraid Tangent currently doesn't have the resources to support this extension. I'll get the docs clarified on that. Please file the bug with whatever fork you're seeing the issue with.
